# Generated by Django 3.2.5 on 2021-07-31 00:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('calendarpage', '0001_initial_squashed_0003_remove_reservation_total_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='member',
            field=models.ManyToManyField(related_name='member_reservation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='representative',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='representative_reservation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='TeamMember',
        ),
    ]
